version: '3.5'
services:
  share:
    image: docker.artifactory.tapsi.tech/doroshke/test_PRODUCTION/production:production
    networks:
      - web
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      #placement:
      #  constraints: [node.labels.share == true]
      labels:
        traefik.port: 3000
        traefik.docker.network: "traefik_webgateway"
        traefik.frontend.rule: "Host:${DOMAIN}"

networks:
  web:
    external: true
    name: traefik_webgateway
